version: 2

jobs:
  build_server:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.4
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd server
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            cd server
            . venv/bin/activate
            python manage.py test
      - deploy:
          name: Deploy server to AWS
          command: |
            cd server
            . venv/bin/activate
            sh deploy/deploy.sh

  build_lambda:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd lambda
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - deploy:
          name: Deploy Lambda to AWS
          command: |
            cd lambda
            . venv/bin/activate
            sh deploy.sh

  build_client:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd client
            npm install
      - deploy:
          name: Build bundle and deploy to S3.
          command: |
            cd client
            sh deploy/deploy.sh


workflows:
  version: 2
  full_deploy:
    jobs:
      - build_server
      - build_lambda:
          requires:
            - build_server
      - build_client:
          requires:
            - build_server
