# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('volume', models.PositiveIntegerField()),
                ('granularity', models.CharField(max_length=5)),
                ('open_bid', models.FloatField()),
                ('high_bid', models.FloatField()),
                ('low_bid', models.FloatField()),
                ('close_bid', models.FloatField()),
                ('open_ask', models.FloatField()),
                ('high_ask', models.FloatField()),
                ('low_ask', models.FloatField()),
                ('close_ask', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('multiplier', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasource.Instrument'),
        ),
    ]
