# Generated by Django 2.0 on 2018-04-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euler', '0007_move_instrument_model_to_core'),
        ('datasource', '0003_change_number_fields_to_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Instrument'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
