# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsample',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=7), size=7),
        ),
        migrations.AlterField(
            model_name='trainingsample',
            name='target',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
