# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:29
from __future__ import unicode_literals

from django.db import migrations


def populate_initial_instruments(apps, schema_editor):
    Instrument = apps.get_model('datasource', 'Instrument')
    Instrument.objects.bulk_create([
        Instrument(name='EUR_USD', multiplier=10000),
        Instrument(name='GBP_USD', multiplier=10000),
        Instrument(name='USD_CAD', multiplier=10000),
        Instrument(name='USD_CHF', multiplier=10000),
        Instrument(name='USD_JPY', multiplier=100),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_instruments),
    ]
