# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_populate_initial_instruments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together=set([('instrument', 'start_time', 'granularity')]),
        ),
    ]
