# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_add_unique_together_for_candles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='close_ask',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='close_bid',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high_ask',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='high_bid',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low_ask',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low_bid',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_ask',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_bid',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
